"""removed auth-type from OTP

Revision ID: 417469bac4de
Revises: a6d1c6c13842
Create Date: 2025-08-31 09:57:49.661025

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "417469bac4de"
down_revision: Union[str, Sequence[str], None] = "a6d1c6c13842"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("otps", "provider_id")
    op.drop_column("otps", "auth_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "otps",
        sa.Column("auth_type", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "otps",
        sa.Column("provider_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
