"""add otp table

Revision ID: a4b5fabfdeac
Revises: ed8afea4154c
Create Date: 2025-07-24 18:30:31.802426

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4b5fabfdeac"
down_revision: Union[str, Sequence[str], None] = "ccf5dc612027"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "otps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("otp_code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("is_active", sa.Integer(), nullable=True),
        sa.Column("provider_id", sa.String(), nullable=True),
        sa.Column("auth_type", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_otps_email"), "otps", ["email"], unique=False)
    op.create_index(op.f("ix_otps_id"), "otps", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_otps_id"), table_name="otps")
    op.drop_index(op.f("ix_otps_email"), table_name="otps")
    op.drop_table("otps")
    # ### end Alembic commands ###
