"""add role field

Revision ID: a6d1c6c13842
Revises: a4b5fabfdeac
Create Date: 2025-08-31 09:15:05.419403

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6d1c6c13842"
down_revision: Union[str, Sequence[str], None] = "a4b5fabfdeac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    userrole_enum = sa.Enum("ADMIN", "USER", name="userrole")
    userrole_enum.create(op.get_bind())

    # Then add the column using the enum type
    op.add_column("users", sa.Column("role", userrole_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # Then drop the enum type
    sa.Enum(name="userrole").drop(op.get_bind())
    # ### end Alembic commands ###
