name: Trivy Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    name: Trivy FS Scan

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner on file system
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          scanners: 'vuln,secret,config'
          ignore-unfixed: true
